#let nonum(eq) = math.equation(block: true, numbering: none, eq)

#let Huplet = math.italic("Huplet")

= Global grid resonances
#v(6pt)

We say that $k$ is *resonant* if all crests of $F_k$ lie on a single rational grid $x = m / M$ (mod 1) for some integer $M ≥ 1$ and indices $m in { 0, …, M - 1 }$.

on the grid:

#nonum[$ g_M = {m/M | m = 0, ..., M-1 } subset RR"/"ZZ $]

== Stationarity on a grid
#v(6pt)

To find the stationary points of $F$, we solve the equation $G = 0$ for the function $G$ defined in @G

Fix $M ≥ 1$ and $m in g_M$. 

If $x = m / M$, write $θ = 2π m / M$. 

Then $G=0$ reads
#nonum[$ k d sin( d θ ) + n sin( n θ ) = 0, $]
when solved in $k$ for $x$ in $g_M$:
$ k = - ( n / d ) sin( 2π n m / M ) / sin( 2π d m / M ) $<k-grid> 
whenever $sin( 2π d m / M ) ≠ 0$.

== Classification theorem (resonant $k$’s)
#v(6pt)

The crests of $F_k$ all lie on a single rational grid if and only if
#table(
columns: 3,
align: (left, left, left),
column-gutter: 1em,
stroke: none,
[$k=0$],   [grid $x=m/n$],         [(the $n$–grid)],
[$k=n/d$], [grid $x=m/(n+d)$],     [(the $(n+d)$–grid)],
[$k→∞$],   [grid $x=m/d$],         [(the $d$–grid)],
)
The excluded case $k=-n/d$ (not in our range $k≥0$) would give the grid $x=m/(|d-n|)$.

== Proof 
#v(4pt)

=== Minimal grid and generating set
#v(6pt)

Assume $k$ is resonant. 

Let $M ≥ 1$ be minimal such that every crest of $F_k$ lie in $g_M$.

Let $S ⊆ ℤ "/" (M ZZ)$ be the set of indices $m$ for which $x = m / M$ is a crest. By minimality of $M$, the additive subgroup generated by $S$ is all of $ℤ "/" (M ZZ)$.

Write $θ_m = 2π m / M$, and define
#nonum[$ s_m = sin( 2π n m / M ), #h(7pt) t_m = sin( 2π d m / M ). $]
Stationarity $G=0$ at $x=m/M$ gives
#nonum[$ k d sin(d θ_m) + n sin(n θ_m) = 0. $]
Hence, for those $m in S$ with $t_m ≠ 0$,
$ s_m / t_m = - (k d) / n =: λ "(constant in "m) .$ 
If $t_m = 0$ for some $m in S$, stationarity forces $s_m = 0$; therefore the ratio is well defined and constant on a nonempty subset $S’ ⊆ S$.

Nonemptiness of $S’$. 

If $t_m = 0$ for every $m in S$, then $sin(2π d m / M)=0$ for all $m in S$; since $S$ generates $ℤ "/" M$, this implies $d ≡ 0$ (mod $M$). Plugging into stationarity forces $s_m=0$ for all $m$, hence $n ≡ 0$ (mod $M$). With $gcd(n,d)=1$ this yields $M=1$, contradicting the presence of multiple crest sites. Thus $S’ ≠ ∅$.

=== Characters and Euler decomposition
#v(6pt)

Fix $M ≥ 1$ and introduce a frequency index $r in ℤ$ (understood mod $M$).

Set $ω = e^(2π i / M)$ and define the character $χ_r : {0,…,M-1} → ℂ$#h(3pt) by
$χ_r (m) = ω^(r m) = e^(2π i r m / M).$

Using Euler’s identities, for every $m in {0,…,M-1}$ we have
#nonum[$ cos( 2π r m / M ) = ( χ_r (m) + χ_(-r)(m) ) / 2 #h(7pt)" and "#h(7pt) sin( 2π r m / M ) = ( χ_r (m) - χ_(-r)(m) ) / ( 2 i ). $]
Hence the sequences $m ↦ s_m$ and $m ↦ t_m$ lie in the real two-dimensional subspaces\
$W_n = "Span"{ χ_n, χ_(-n) }, #h(7pt) W_d = "Span"{ χ_d, χ_(-d) } $
of the function space on $ℤ "/ "M$.

Define $f = s - λ t$. We have $f(m)=0$ for all $m in S’$ (and also at those $m in S$ with $s_m=t_m=0$).

==== Lemma (character separation)
#v(2pt)

If none of the congruences
$n ≡ 0, #h(6pt) d ≡ 0, #h(6pt) d ≡ ± n #h(6pt) (mod M)$
holds, then there exist $m_1, m_2, m_3, m_4 in S$ such that the $4×4$ matrix with entries $χ_r (m_j)$ for $r in { n, -n, d, -d }$ and $j=1,…,4$ is invertible. In particular, any linear combination
$a χ_n + b χ_(-n) + c χ_d + e χ_(-d)$
that vanishes at $m_1,…,m_4$ is identically zero on $ℤ "/" M$.

Idea. Distinct characters on $ℤ "/" M$ are linearly independent. The determinant of the evaluation matrix is a nonzero trigonometric polynomial in the sample points; because $S$ generates $ℤ "/" M$, we can pick $m_j in S$ avoiding its (finite) zero set.

=== From vanishing on a generating set to span coincidence
#v(2pt)

By the lemma, unless one of the congruences above holds, the only combination of ${ χ_n, χ_(-n), χ_d, χ_(-d) }$ vanishing on $m_1,…,m_4$ is the zero one. Since $f$ is such a combination and $f(m)=0$ for all $m in S’$, we conclude $f≡0$ on $ℤ "/" M$, i.e.
$s = λ t$ as functions on $ℤ "/" M$.

Therefore either $W_n = W_d$ (span coincidence), or one of the congruences holds. But $W_n = W_d$ happens iff ${ +n, -n } ≡ { +d, -d }$ (mod $M$), i.e. exactly when
$d ≡ ± n #h(4pt) (mod M),$
or else when $n ≡ 0$ (mod $M$) or $d ≡ 0$ (mod $M$). In all cases we obtain the three options:
#nonum[$ M = n, #h(6pt) M = d, #h(6pt) M = n + d #h(4pt) ("or" #h(4pt) M = | d - n |). $]

=== Matching the grids with parameter values
#v(2pt)

These grids occur precisely at:
-	$k = 0$  → $M = n$ (the $n$–grid);
-	$k = n / d$ → $M = n + d$ (threshold).\ Indeed, $k d sin(d θ) + n sin(n θ) = 0 #h(6pt) <==> #h(6pt) 2 sin((d+n) θ / 2) cos((d-n) θ / 2) = 0,$\ and the crest test selects $θ = 2π m / (n + d)$;
-	$k → ∞$ → $M = d$ (dominance of the $d$–term).

The case $M = | d - n |$ corresponds to $k = - n / d$ (same factorization with opposite sign), which lies outside our range $k ≥ 0$.

=== Poles do not create extra cases
#v(2pt)

Indices with $t_m = sin(2π d m / M) = 0$ make the explicit ratio in  undefined, but then $s_m = 0$ as well; they can be discarded in forming $S’$. They do not yield any proportionality beyond the three congruence classes above.

Conclusion. The only resonant parameters with $k ≥ 0$ are
$k in { 0, #h(3pt) n / d, #h(3pt) ∞ },$\ 
with global grids $M in { n, #h(3pt) n + d, #h(3pt) d }$, respectively. □