#let nonum(eq) = math.equation(block: true, numbering: none, eq)
#let Huplet = math.italic("Huplet")

= Introduction
#v(6pt)

This article studies the geometry of rhythmic “interference patterns” generated by two
integer frequencies. Fix integers $d>n>0$, and let $x in ℝ \/ ℤ$ denote phase on the unit
cycle. For a modulation parameter $k ≥ 0$, we consider the function
$ F_k (x) = k cos(2π d x) + cos(2π n x). $ <Fk>
Musically, $cos(2π n x)$ marks the regular $n$–tuplet, and $cos(2π d x)$ marks the
$d$–tuplet. Varying $k$ continuously blends these two accent structures.

Our approach is analytic: accents correspond to *crests*, i.e. points where the
first derivative of $F_k$ vanishes and the second is negative. Writing
$ G_k (x) = ∂_x F_k (x) = - 2π ( k d sin(2π d x) + n sin(2π n x) ) $<G>  and $ H_k (x) = ∂_(x x) F_k (x) = - (2π)^2 ( k d^2 cos(2π d x) + n^2 cos(2π n x) ), $<H>  the condition
$G_k (x)=0$, $H_k (x)<0$ selects the musically relevant maxima. At $k=0$, the crests lie
exactly at $x=i/n$. As $k$ increases, each of these $n$ initial crests continues along a
well-defined trajectory in the phase variable. Tracking these trajectories is the starting
point of the paper.

---

== Crest trajectories

#v(6pt)
For each index $i$ in ${0,…,n-1}$, let $X_i (k)$ be the continuous solution of
$G_k (X_i (k))=0$ that satisfies $X_i (0)=i/n$ and $H_k (X_i (k))<0$.
Between fold points where both derivatives vanish, the branch $X_i$ is real-analytic.
A phasor reparametrization $θ=2π x$ yields an explicit expression for the value of $k$
that makes phase $θ$ stationary:
$ k(θ) = - (n/d) sin(n θ) / sin(d θ). $<k-theta>
This formula allows us to follow the crest trajectories through the singularities of
$k(θ)$ and to analyze their crossings and bifurcations.

A central observation is that *global alignment* of the $n$ crests onto a single rational
grid occurs only at three values of $k$, namely
$ k in {0, n/d, ∞}. $
At these resonant points the crests lie respectively on the $1/n$–grid, the
$1/(n+d)$–grid, and the $1/d$–grid. The latter two cases correspond to the Euclidean
rhythms $E(n,n+d)$ and $E(n,d)$.

---

== Spacing vectors: from crest trajectories to Huplets and Quplets

#v(6pt)
Ordering the $n$ crest phases $X_i(k)$ in circular order defines an anchored spacing
vector that we call the #Huplet. Its entries record the successive intervals between
crests. As $k$ increases, the #Huplet develops a remarkably rigid structure, and in the
limit $k→∞$ it converges to a vector
$ Q(n,d) $
that we call the *Quplet*. This limit is a rotation-constrained Euclidean rhythm,
canonically selected by the continuation of the crest trajectories.

We prove two organizing identities: a threshold–extension relation
#nonum[$ Huplet(n,d,n/d) = Q(n,n+d), $]
and a Euclidean reduction
#nonum[$ Q(n,d) = Huplet(n,d-n,n/(d-n)). $]
Together, they show that Quplets interpolate the Euclidean family in a way determined
by crest continuation rather than by discrete optimization.

---

== Geometry in the simplex

#v(6pt)
The collection of all $Q(n,d)$ for fixed $n$ exhibits unexpected geometric regularities.
When $d$ varies through a fixed residue class modulo $n$, the Quplets form a straight
line in the $(n-1)$–simplex $Σ_n = { q in ℝ^n_+ : sum q_i = 1 }$. This colinearity reflects
a rotation-selection principle: among all rotations of the Euclidean rhythm $E(n,d)$, the
crest dynamics pick the one that is closest (in circular distance) to the regular
$n$–tuplet.

A complementary projection viewpoint characterizes $Q(n,d)$ as the image of the
$(d-1)$–simplex barycenter under a structured block–sum matrix encoding the anchored
$d$–grid onsets. This topological interpretation provides a global picture in which
crest trajectories, Euclidean rhythms, and simplex geometry arise from a single analytic
mechanism.

---

== Outline

#v(6pt)
- Section 2 studies crests of $F_k$ and the analytic continuation of $X_i(k)$.
- Section 3 analyzes the resonant values $k in {0, n/d, ∞}$ and the resulting spacing
  vectors.
- Section 4 develops the Huplet–Quplet framework and its Euclidean connections.
- Section 5 introduces the geometric interpretation in the simplex and projection
  viewpoint.