= Proof of the global grid resonances 

Fix integers $d > n > 0$ with $gcd(n, d) = 1$, and $k ≥ 0$. 

Say that k is *resonant* if all crests of 
$ F_k (x) = k cos(2π d x) + cos(2π n x) $
lie on a single rational grid $x = m / M (mod 1)$ for some integer $M ≥ 1$.

== Step 1 — Minimal grid and generating set

Assume $k$ is resonant. 

Let $M ≥ 1$ be *minimal* such that every crest of $F_k$ has the form $x = m / M (mod 1)$.

Let $S ⊆ ℤ "/" M$ be the set of indices m for which $x = m / M$ is a crest.

By minimality of $M$, the additive subgroup generated by $S$ is all of $ℤ "/" M$.

Write $θ_m = 2π m / M$, and define
$ s_m = sin( 2π n m / M ),#h(7pt)   t_m = sin( 2π d m / M ). $
Stationarity $G = 0$ at $x = m / M$ reads
$ k d sin(d θ_m) + n sin(n θ_m) = 0, $
hence, for those $m$ in $S$ with $t_m ≠ 0$,
$ s_m / t_m = - (k d) / n =: λ "(constant in m)." $ 
If $t_m = 0$ for some $m in S$, then necessarily $s_m = 0$ as well (otherwise stationarity fails).

Thus the ratio is well defined and constant on a nonempty subset $S' ⊆ S$.

== Step 1 — Minimal grid and generating set

Assume $k$ is resonant. 

Let $M ≥ 1$ be minimal such that every crest of $F_k$ has the form $x = m / M$ (mod 1).

Let $S ⊆ ℤ "/" M$ be the set of indices $m$ for which $x = m / M$ is a crest. By minimality of $M$, the additive subgroup generated by $S$ is all of $ℤ "/" M$.

Write $θ_m = 2π m / M$, and define
$ s_m = sin( 2π n m / M ), #h(7pt) t_m = sin( 2π d m / M ). $
Stationarity $G = 0$ at $x = m / M$ reads
$ k d sin( d θ_m ) + n sin( n θ_m ) = 0. $
Hence, for those $m in S$ with $t_m ≠ 0$,
$ s_m / t_m = - ( k d ) / n =: λ "(constant in" m) .$  If $t_m = 0$ for some $m in S$, stationarity forces $s_m = 0$ as well; therefore the ratio is well defined and constant on a nonempty subset $S’ ⊆ S$.

Nonemptiness of $S’$. If $t_m = 0$ for every $m in S$, then $sin( 2π d m / M ) = 0$ for all $m in S$; since $S$ generates $ℤ "/"M$, this implies $d ≡ 0$ (mod $M$). Plugging into stationarity forces $s_m = 0$ for all $m$, hence $n ≡ 0$ (mod $M$). With $gcd(n,d)=1$ this yields $M = 1$, contradicting the presence of multiple crest sites. Thus $S’ ≠ ∅$.

== Step 2 — Character formulation

Let $ω = e^(2π i / M)$ and $χ_r (m) = ω^(r m)$ be the characters on ℤ / M.

Then
$ sin( 2π r m / M ) = ( χ_r (m) - χ_(-r)(m) ) / ( 2 i ). $
Hence the sequences $m ↦ s_m$ and $m ↦ t_m$ lie in the real two-dimensional subspaces
$ W_n = "Span"{ χ_n, χ_(-n) }, #h(7pt)  W_d = "Span"{ χ_d, χ_(-d) } $
of the function space on ℤ / M.

Define $f = s - λ t$. We have $f(m) = 0$ for all $m in S'$ (and also at those $m in S$ with $s_m = t_m = 0$).

== Step 3 — From vanishing on a generating set to span coincidence

Because $S$ generates $ℤ "/" M$, there exist four indices in $S$ on which the 4-character family 
${ χ_n, χ_(-n), χ_d, χ_(-d) }$ is pointwise linearly independent unless one of the congruences
$ n ≡ 0,#h(5pt) d ≡ 0,#h(5pt)  d ≡ ± n #h(5pt) (mod M) $
holds. If none of these congruences holds, the only combination of these four characters
that vanishes on those four points is the zero combination; by additivity, $f ≡ 0$ on $ℤ "/" M$,
so $s = λ t$ as functions on $ℤ "/" M$.

Therefore, either $W_n = W_d$ (span coincidence), or one of the congruences above holds.

But $W_n = W_d$ happens *iff* ${ +n, -n } ≡ { +d, -d } (mod M)$, i.e. exactly when
$ d ≡ ± n \; (mod #h(3pt) M), $
or else when $n ≡ 0 (mod M)$ or $d ≡ 0 (mod M)$. In all cases we obtain the three options:
$ M = n,  M = d, M = n + d #h(3pt) ("or" #h(3pt) M = | d - n |). $

== Step 4 — Matching the grids with parameter values

These grids occur precisely at:
- $k = 0  → M = n$ (the $n$-grid);
- $k = n / d → M = n + d$ (threshold).\ Indeed,
  $k d sin(d θ) + n sin(n θ) = 0  ⇔  2 sin((d+n) θ / 2) cos((d-n) θ / 2) = 0,$\
  and the crest test selects $θ = 2π m / (n + d)$;
- $k → ∞ → M = d$ (dominance of the $d$-term).

The case $M = abs(d - n)$ corresponds to $k = - n / d$ (same factorization with opposite sign),
which lies outside our range $k ≥ 0$.

== Step 5 — Poles do not create extra cases

Indices with $t_m = sin(2π d m / M) = 0$ make the explicit ratio undefined,

but then $s_m = 0$ as well; they can be discarded in forming $S'$. 

They do not yield any additional proportionality beyond the three congruence classes above.

Hence the only resonant parameters with k ≥ 0 are
$ k in { 0, #h(3pt) n / d, #h(3pt) ∞ }, $
with global grids $M in { n, n + d, d }$, respectively. □