#let nonum(eq) = math.equation(block: true, numbering: none, eq)

#let Huplet = math.italic("Huplet")

= Appendix A: Rational crests and allowed grids
#v(8pt)

In this appendix we show that, if all crest positions $X_i(k)$ are rational modulo $1$, then the parameter $k$ must be one of the three regimes
#nonum[$ k in { 0, n/d, infinity } $]
(where $infinity$ denotes the limit $k -> infinity$). The argument has two steps: an elementary arithmetic lemma and a short discrete-Fourier lemma.

== Step 1: common denominator
#v(6pt)

We first reduce the hypothesis “all crests are rational” to the existence of a *single* rational grid.

=== Lemma (common grid for rational crests)
#v(4pt)

Suppose that for some $k >= 0$, all crest positions $X_i(k)$ are rational modulo $1$:\
$X_i(k) = a_i / b_i$ with $gcd(a_i,b_i)=1$. Let
#nonum[$ M = lcm(b_0, dots, b_(n-1)) $.]
Then each crest can be written as $X_i(k) = m_i / M$ (mod $1$) for some integer $m_i$. Thus all crests lie on the grid
#nonum[$ g_M = { m/M : m = 0, dots, M-1 } subset ℝ"/"ℤ $.]

If $M$ is chosen minimal with this property, then the set of indices
#nonum[$ S = { m_i (mod M) } $]
generates the cyclic group $ℤ"/"(M ℤ)$.

*Proof.* The existence of such $M$ is immediate from the least common multiple. If the subgroup generated by $S$ were proper, all crests would already lie on a smaller grid $g_(M')$ with $M'<M$, contradicting minimality. □

== Step 2: discrete-Fourier lemma
#v(6pt)

Fix a minimal $M$ such that all crests lie on $g_M$. Write $θ_m = 2π m / M$ and define
#nonum[$ s_m = sin(2π n m / M), quad t_m = sin(2π d m / M). $]

Stationarity $G_k=0$ at $x=m/M$ gives (see @G):
#nonum[$ k d t_m + n s_m = 0. $]

Let $S subset ℤ"/"(M ℤ)$ be the crest indices. As $M$ is minimal, $S$ generates $ℤ"/"(M ℤ)$. There is a nonempty subset $S' subset S$ where $t_m != 0$ and
#nonum[$ s_m / t_m = -(k d)/n =: λ $]
is constant.

Using Euler identities, the sequences $m mapsto s_m$ and $m mapsto t_m$ lie in the spans
#nonum[$
  W_n = { cos(2π n m / M), sin(2π n m / M) },
  quad
  W_d = { cos(2π d m / M), sin(2π d m / M) }.
$]

Define $f = s - λ t$. Then $f$ is a linear combination of the four modes
#nonum[$ cos(2π n m / M), sin(2π n m / M), cos(2π d m / M), sin(2π d m / M) $]
and satisfies $f(m)=0$ for all $m in S'$ (and for any $m$ with $s_m=t_m=0$).

=== Lemma (allowed denominators)
#v(4pt)

With $M$ minimal as above, one must have
#nonum[$ M in { n, d, n+d, |d-n| }. $]

*Idea of proof.* If none of the congruences
#nonum[$ n equiv 0, quad d equiv 0, quad d equiv p m n quad (mod M) $]
holds, then the four modes above are linearly independent on $ℤ"/"M$, hence no nonzero combination can vanish on a generating set $S$. Thus one of the congruences must hold, which gives exactly the four values of $M$ listed. □

== Step 3: matching denominators with parameters
#v(6pt)

We use the factorization
#nonum[$
  k d sin(d θ)
  + n sin(n θ)
  =
  (k d + n) sin((d+n) θ / 2) cos((d-n) θ / 2)
  +
  (k d - n) sin((d-n) θ / 2) cos((d+n) θ / 2).
$]

A direct verification shows:

- $M=n$ occurs at $k=0$;
- $M=n+d$ occurs exactly at $k=n/d$;
- $M=d$ occurs as $k -> infinity$;
- $M = |d-n|$ occurs at $k=-n/d$ (excluded since $k >= 0$).

We obtain the classification.

=== Theorem (rational crest parameters)
#v(4pt)

If for some $k >= 0$ all crest positions $X_i(k)$ are rational modulo $1$, then
#nonum[$ k in { 0, n/d, oo }. $]

*Proof.* By the common-denominator lemma, the crests lie on a minimal grid $g_M$. By the allowed-denominator lemma, $M in { n, d, n+d, |d-n| }$. Matching with the factorized derivative shows that only $k=0$, $k=n/d$, and $k -> infinity$ occur for $k >= 0$. □

#v(6pt)

*Remark.* For $n=3$, the two interior crest branches are symmetric about $x=1/2$, so any rational alignment in $]0,1[$ occurs simultaneously for both. This symmetry does not create new rational crest parameters.